# Assignment of Week 1 

Q#1 Write a NumPy program to create an array of all even integers from 30 to 70.

In [1]:
import numpy as np
even_nbr = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:", even_nbr)

Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Q#2 Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [2]:
random_array = np.random.randn(15)
print("Array of 15 random numbers from standard normal distribution:", random_array)

Array of 15 random numbers from standard normal distribution: [-0.4597532   0.55961769  0.70445748  0.14845739 -0.91539564 -1.52407817
  0.1076366   0.01662245 -0.95962236  2.15484993 -0.30192169  0.28744986
  0.58131312  0.79982201  0.06785372]


Q#3 How to compute the cross-product of two matrices in NumPy?

In [3]:
m1 = np.array([[2, 6], [9, 5]])
m2 = np.array([[3, 7], [8, 7]])
cross_product = np.cross(m1, m2)
print("Cross-product of two matrices:")
print(cross_product)

Cross-product of two matrices:
[-4 23]


Q#4 How to compute the determinant of an array using NumPy?

In [4]:
ar = np.array([[6, 4], [7, 2]])
determinant = np.linalg.det(ar)
print("Determinant of the array:", determinant)

Determinant of the array: -15.999999999999998


Q#5 How to create a 3x3x3 array with random values using NumPy?

In [5]:
RA = np.random.random((3, 3, 3))
print("3x3x3 array with random values:")
print(RA)

3x3x3 array with random values:
[[[0.47989323 0.02543295 0.34308905]
  [0.67219734 0.99624144 0.73911596]
  [0.43312803 0.32471179 0.5061351 ]]

 [[0.06995057 0.09305554 0.09296824]
  [0.89295089 0.54303307 0.57827727]
  [0.13924585 0.25024222 0.1109937 ]]

 [[0.40617223 0.72477766 0.78550826]
  [0.66790537 0.5060138  0.84259728]
  [0.49364864 0.81091791 0.61010695]]]


Q#6 How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?

In [7]:
random_5x5 = np.random.random((5, 5))
print("5x5 array with random values:")
print(random_5x5)
c = np.min(random_5x5)
d = np.max(random_5x5)
print("Minimum value:", c)
print("Maximum value:", d)

5x5 array with random values:
[[0.13971122 0.11924293 0.97625986 0.65778421 0.36624366]
 [0.9970849  0.91276277 0.4471132  0.76302775 0.82598643]
 [0.71888228 0.59506576 0.25421772 0.79928792 0.4760688 ]
 [0.08708639 0.05225336 0.18206117 0.43691669 0.27607639]
 [0.17846747 0.53481242 0.8409858  0.2331371  0.32384072]]
Minimum value: 0.052253357480292806
Maximum value: 0.9970849000645767


Q#7 How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [8]:
array = np.array([[9, 8, 7], [6, 5, 4]])
mean = np.mean(array, axis=1)
std_deviation = np.std(array, axis=1)
variance = np.var(array, axis=1)
print("Mean along the second axis:", mean)
print("Standard deviation along the second axis:", std_deviation)
print("Variance along the second axis:", variance)

Mean along the second axis: [8. 5.]
Standard deviation along the second axis: [0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667]
